import './globals.css'


export const metadata = {
  title: 'trello web 2.0',
  description: 'Generated by mnour ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
